export const emailTheme = {
  color: {
    background: "#fdf6f8",
    card: "#ffffff",
    plum: "#6e5a8f",
    accent: "#2277b6",
    rose: "#dda99e",
    roseInk: "#422d7d",
    lavender: "#b39ddb",
    lavenderSoft: "#ebe3f5",
    mint: "#a7e8d0",
    banana: "#fde293",
    pink: "#fbd3e0",
    pinkSoft: "#fbeaf1",
    cream: "#faeede",
    ink: "#333333",
    inkSoft: "#666666",
    muted: "#f4eef8",
    mutedInk: "#6b6076",
    border: "#ebd9e8",
  },
  font: {
    heading: "Fredoka, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    body: "Assistant, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
  },
  radius: "28px",
} as const
